name: llvm
on:
  push:
    paths:
      - llvm/**
      - .github/workflows/llvm.yml
  pull_request:
    paths:
      - llvm/**
      - .github/workflows/llvm.yml
  workflow_dispatch:
env:
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
  linux-x86_64:
    runs-on: ubuntu-18.04
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
  redeploy:
    needs: linux-x86_64
    runs-on: ubuntu-18.04
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/redeploy@actions
  samples:
    needs: redeploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          mvn -B -U -e clean compile exec:java -Pfactorial
          mvn exec:java -Pemit-bitcode
          mvn exec:java -Pevaluate-bitcode
          mvn exec:java -Porcjit
        working-directory: llvm/samples/llvm
